#!/usr/bin/env bash
# Bash script that displays information about subdomains.
if [ "$1" ];
then
	dig "$1".diekkan.tech | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk "{split("$1", a, "."); print The subdomain"a[1]" is a "$4" record and points to "$5"}"
else
	dig lb-01.diekkan.tech | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{split($1, a, "."); print "The subdomain " a[1] " is a " $4 " record and points to " $5}'
	dig web-01.diekkan.tech | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{split($1, a, "."); print "The subdomain " a[1] " is a " $4 " record and points to " $5}'
	dig web-02.diekkan.tech | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{split($1, a, "."); print "The subdomain " a[1] " is a " $4 " record and points to " $5}'
fi
