#!/usr/bin/env bash
# The typical FizzBuzz but in Bash script.

i=1;
until [ $i == 101 ];
do
	if [ $((i%3)) == 0 ] && [ $((i%5)) == 0 ];
	then
		echo "FizzBuzz"
		i=$((i+1))
		continue
	elif [ $((i%3)) == 0 ];
	then
		echo "Fizz"
	elif [ $((i%5)) == 0 ];
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	i=$((i+1))
done
