#!/usr/bin/env bash
# Running nginx as nginx user
sudo chmod -R ugo+rw /etc/nginx/
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.config
ln -sf /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo -u nginx service nginx start
