#!/usr/bin/env bash
sudo chmod -R ugo+rw /etc/nginx/
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo -u nginx service nginx start
